### ISSUE TITLE
AMShimmer not stopping with UIVIew()

### ISSUE THREAD

**Issue by kiransarvaiya** [Abedalkareem/AMShimmer#3]
Hello,
Am Facing issues related stop Shimmer following my few lines of code.
   //MARK: - IBoutlet 
    @IBOutlet weak var vwFamilyDoctor: UIView!

when I called API services I called this line
        AMShimmer.start(for: vwFamilyDoctor)
and that's work properly
but after getting a response I called 
        AMShimmer.stop(for: vwFamilyDoctor)
but this was not working.

**Comment by Abedalkareem** [comment]
Hi!
what kind of subviews the  ```vwFamilyDoctor``` has?
can you show me the view hierarchy?

**Comment by kiransarvaiya** [comment]
Please See hierarchy
![Screenshot 2019-05-21 at 11 17 24 AM](https://user-images.githubusercontent.com/16743405/58071382-1c461800-7bba-11e9-9dea-5ac6b9c825c6.png)

please see UI
![Screenshot 2019-05-21 at 11 17 46 AM](https://user-images.githubusercontent.com/16743405/58071383-1cdeae80-7bba-11e9-80e2-a8e01b438d4c.png)

**Comment by Abedalkareem** [comment]
are you sure that you are applying the stop(for:) function on the same instance of the vwFamilyDoctor object? 
because as I see in your hierarchy there are two vwFamilyDoctor views?

**Comment by kiransarvaiya** [comment]
actually, I applied for the main vwFamilyDoctor and inside vwFamilyDoctoris card so I want to shimmer load the main view.

**Comment by Abedalkareem** [comment]
Are you using the stop(for:) in the main thread?
can you try to replace your stop code with this one:
DispatchQueue.main.async {
        AMShimmer.stop(for: self.vwFamilyDoctor)
}

**Comment by kiransarvaiya** [comment]
still not working

**Comment by Abedalkareem** [comment]
I have a question, is this view inside a table view?

**Comment by kiransarvaiya** [comment]
No this is one of child view inside scroll view

**Comment by Abedalkareem** [comment]
The issue fixed (v1.0.6), thank you for reporting the issue!

**Comment by kiransarvaiya** [comment]
Not working
