### ISSUE TITLE
Not working on UIButton inside UITableview Cell

### ISSUE THREAD

**Issue by dipsvaishnav** [Abedalkareem/AMShimmer#6]
not working on UIButton inside UITableview Cell after stop UIButton image not showing

**Comment by Abedalkareem** [comment]
Hi dipsvaishnav,

Can you please share the view hierarchy?

Thank you.

**Comment by Abedalkareem** [comment]
I have added a button inside the example and it's working fine. check the example.
I'm waiting for your reply, I'll close the issue for now and if you are still facing this issue please reopen it and share the view hierarchy.

Thank you!
